name: Gitstart Pull
on:
  workflow_dispatch:
  schedule:
     # actually, ~5 minutes is the highest
     # effective frequency you will get
    - cron:  '* * * * *'
jobs:
  Gitstart Pull:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - id: sync
        uses: gitstart/pull@v0.0.3
        with:
          upstream: https://github.com/gitstart/hey 
